### ISSUE TITLE
Where on earth is `Some site description will go here`?

### ISSUE THREAD

**Issue by joewheaton** [AnabranchSolutions/AnabranchSolutions.github.io#2]
On the front page, there is a horrible `Some site description will go here` subheader under the home page in `index.md`. I've searched every damn file in the repo and can't find where you control this. @MattReimer  do you know?

**Comment by philipbaileynar** [comment]
@joewheaton  it's on line 5 of the `_config.yml` file in the root:

https://github.com/AnabranchSolutions/AnabranchSolutions.github.io/blob/master/_config.yml#L5

**Comment by joewheaton** [comment]
Thanks!
